import type { DirectoryAlumnus } from "../../../../types";

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=400&q=80`;

export const DIRECTORY: DirectoryAlumnus[] = [
  {
    id: "1",
    name: "Capt. Ibrahim Bello",
    photo: img("photo-1614249706471-36016b37b63c"),
    discipline: "B.Sc. Nautical Science",
    graduationYear: "2022",
    role: "Navigation Officer",
    company: "Nigerian Navy",
    location: "Lagos, Nigeria",
  },
  {
    id: "2",
    name: "Engr. Nneka Eze",
    photo: img("photo-1563132337-f159f484226c"),
    discipline: "B.Eng. Marine Engineering",
    graduationYear: "2023",
    role: "Chief Engineer",
    company: "NLNG",
    location: "Bonny, Nigeria",
  },
  {
    id: "3",
    name: "Dr. Olayinka Adeyemi",
    photo: img("photo-1507003211169-0a1dd7228f2d"),
    discipline: "B.Sc. Marine Economics",
    graduationYear: "2021",
    role: "Port Operations Manager",
    company: "Apapa Port Complex",
    location: "Lagos, Nigeria",
  },
  {
    id: "4",
    name: "Aisha Mohammed",
    photo: img("photo-1500648767791-00dcc994a43e"),
    discipline: "B.Sc. Meteorology",
    graduationYear: "2024",
    role: "Climate Researcher",
    company: "NIMET",
    location: "Abuja, Nigeria",
  },
  {
    id: "5",
    name: "Engr. Musa Ibrahim",
    photo: img("photo-1519085360753-af0119f7cbe7"),
    discipline: "B.Eng. Marine Engineering",
    graduationYear: "2020",
    role: "Marine Superintendent",
    company: "Maersk Line",
    location: "Rotterdam, Netherlands",
  },
  {
    id: "6",
    name: "Chioma Nwafor",
    photo: img("photo-1531123897727-8f129e1688ce"),
    discipline: "B.Sc. Maritime Transport & Logistics",
    graduationYear: "2022",
    role: "Logistics Coordinator",
    company: "MSC Nigeria",
    location: "Port Harcourt, Nigeria",
  },
  {
    id: "7",
    name: "Tamuno Fubara",
    photo: img("photo-1573497019940-1c28c88b4f3e"),
    discipline: "B.Sc. Nautical Science",
    graduationYear: "2023",
    role: "Deck Officer",
    company: "West Africa–Europe container line",
    location: "Warri, Nigeria",
  },
  {
    id: "8",
    name: "Grace Nnadi",
    photo: img("photo-1573496359142-b8d87734a5a2"),
    discipline: "B.Sc. Fisheries & Aquaculture",
    graduationYear: "2019",
    role: "Aquaculture Research Lead",
    company: "Federal Dept. of Fisheries",
    location: "Calabar, Nigeria",
  },
  {
    id: "9",
    name: "Femi Adeyemi",
    photo: img("photo-1544005313-94ddf0286df2"),
    discipline: "B.Eng. Naval Architecture",
    graduationYear: "2021",
    role: "Naval Architect",
    company: "Damen Shipyards",
    location: "Lagos, Nigeria",
  },
  {
    id: "10",
    name: "Hassan Yusuf",
    photo: img("photo-1552058544-f2b08422138a"),
    discipline: "B.Sc. Nautical Science",
    graduationYear: "2018",
    role: "Master Mariner",
    company: "Bourbon Offshore",
    location: "Singapore",
  },
  {
    id: "11",
    name: "Ngozi Eze",
    photo: img("photo-1517841905240-472988babdf9"),
    discipline: "B.Sc. Marine Economics",
    graduationYear: "2020",
    role: "Freight Analyst",
    company: "SIFAX Group",
    location: "Lagos, Nigeria",
  },
  {
    id: "12",
    name: "Seun Adeleke",
    photo: img("photo-1500917293891-ef795e70e1f6"),
    discipline: "B.Eng. Marine Engineering",
    graduationYear: "2022",
    role: "Rig Engineer",
    company: "Seplat Energy",
    location: "Warri, Nigeria",
  },
  {
    id: "13",
    name: "Chidinma Okafor",
    photo: img("photo-1508214751196-bcfd4ca60f91"),
    discipline: "B.Sc. Maritime Transport & Logistics",
    graduationYear: "2024",
    role: "Supply Chain Analyst",
    company: "Dangote Group",
    location: "Lagos, Nigeria",
  },
  {
    id: "14",
    name: "Rotimi Oladele",
    photo: img("photo-1519345182560-3f2917c472ef"),
    discipline: "B.Sc. Nautical Science",
    graduationYear: "2017",
    role: "Harbour Pilot",
    company: "Nigerian Ports Authority",
    location: "Onne, Nigeria",
  },
  {
    id: "15",
    name: "Amarachi Eze",
    photo: img("photo-1614289371518-722f2615943d"),
    discipline: "B.Sc. Meteorology",
    graduationYear: "2023",
    role: "Weather Forecaster",
    company: "NIMET",
    location: "Port Harcourt, Nigeria",
  },
  {
    id: "16",
    name: "Musa Abdullahi",
    photo: img("photo-1541823709867-1b206113eafd"),
    discipline: "B.Eng. Naval Architecture",
    graduationYear: "2019",
    role: "Structural Design Engineer",
    company: "Hyundai Heavy Industries",
    location: "Ulsan, South Korea",
  },
  {
    id: "17",
    name: "Isioma Nwachukwu",
    photo: img("photo-1487412720507-e7ab37603c6f"),
    discipline: "B.Sc. Fisheries & Aquaculture",
    graduationYear: "2021",
    role: "Sustainability Officer",
    company: "WorldFish Nigeria",
    location: "Abuja, Nigeria",
  },
  {
    id: "18",
    name: "Kelechi Obi",
    photo: img("photo-1438761681033-6461ffad8d80"),
    discipline: "B.Sc. Marine Economics",
    graduationYear: "2018",
    role: "Director, Public Affairs",
    company: "NMU Alumni Association",
    location: "Lagos, Nigeria",
  },
  {
    id: "19",
    name: "Faith Williams",
    photo: img("photo-1472099645785-5658abf4ff4e"),
    discipline: "B.Sc. Maritime Transport & Logistics",
    graduationYear: "2020",
    role: "Terminal Operations Officer",
    company: "APM Terminals",
    location: "Lagos, Nigeria",
  },
  {
    id: "20",
    name: "Kenny Bankejesu",
    photo: img("photo-1544723795-3fb6469f5b39"),
    discipline: "B.Eng. Marine Engineering",
    graduationYear: "2023",
    role: "Junior Engineer",
    company: "Nigerian Agip Exploration",
    location: "Port Harcourt, Nigeria",
  },
];
